# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

# Note that this file is NOT used to automatically manage dependencies for the
# local compute target. To provision these dependencies locally, run:
# conda env update --file conda_dependencies.yml

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For managing Spark packages and configuration, see spark_dependencies.yml.

name: infersent
channels:
  - soumith
dependencies:
  # The python interpreter version.
  - python=3.5
  - scikit-learn
  - matplotlib
  - pytorch
  - torchvision

  # Required for Jupyter Notebooks.
  - ipykernel=4.6.1
  
  - pip:
    - nltk
    
    # The API for Azure Machine Learning Model Management Service.
    # Details: https://github.com/Azure/Machine-Learning-Operationalization
    - azure-ml-api-sdk==0.1.0a10    